version: '3.9'

services:
  backend:
    #use Dockerfile in localDirectory
    build: .

    ports:
      #localPort:ContainerPort
      - 8000:3000

    volumes:
      #localDirectory:ContainerDirectory (WORKDIR)
      - .:/app
    
    depends_on: 
      - db

  db:
    image: mysql:5.7.22
    restart: always

    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

    volumes:
      #localDirectory:ContainerDirectory
      - .dbdata:/var/lib/mysql
