version: '3.9'

services:

  db:
    container_name: mysql_db
    image: mysql:5.7.22
    restart: always

    environment:
      MYSQL_DATABASE: ngnestjs
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

    ports:
      #localPort:ContainerPort
      - 33066:3306

    volumes:
      #localDirectory:ContainerDirectory
      - .dbdata:/var/lib/mysql
  

  backend:
    container_name: nest_backend
    #use Dockerfile in localDirectory
    build: .

    ports:
      #localPort:ContainerPort
      - 8000:3000

    volumes:
      #localDirectory:ContainerDirectory (WORKDIR)
      - .:/usr/src/app
      - /usr/src/app/node_modules
    
    depends_on: 
      - db